<a href="https://colab.research.google.com/github/AdieshwarReddy/2311cs020426-sigma-section-day3/blob/main/pandas(21_1_2025)1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#  day 8 notes
def calculateArea(r):
  area = 3.14 * r * r
  return area
calculateArea(10)

314.0

In [ ]:
def area(l,s):
  r=l*s
  return r
  area(10,20)

In [ ]:
def area (radius,length,width):
  aoc=3.14*radius*radius
  aor=length*width
  return aoc,aor
area(1,2,33)

(3.14, 66)

In [ ]:
def area (radius,length,width):
  aoc=3.14*radius*radius
  aor=length*width
  return {"Area of rectangle  is:" :aor,"area of circle is:":  aoc }
area(1,2,33)

{'Area of rectangle  is:': 66, 'area of circle is:': 3.14}

In [ ]:
aor,aoc=area(radius=6,length=2,width=3)
aor
aoc

'area of circle is:'

In [ ]:
s=area(radius=6,length=2,width=3)
s
type(s)


dict

In [ ]:
s["Area of rectangle  is:"]

6

In [ ]:
t='hyderabad 500008 Telangana'
t

'hyderabad 500008 Telangana'

In [39]:
def count(t):
    alpha = 0
    space = 0
    digit = 0

    for i in t:
        if i.isalpha():
            alpha += 1
        if i.isspace():
            space += 1
        if i.isdigit():
            digit += 1

    return alpha, space, digit


In [ ]:
count("hyderabad     22321 uwywy2h")

(1, 0, 0)

In [ ]:
#
def nom(T):
  r1=""
  for i in T:
    if i.isdigit()==False:
      r1+=i
  return r1

In [ ]:
nom("1223   2 2 dd")

'     dd'

In [ ]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [ ]:
numbers = [1, 2, 3, 4, 5]


updated_numbers = [i + 7 for i in numbers]


print("Original List:", numbers)
print("Updated List:", updated_numbers)



Original List: [1, 2, 3, 4, 5]
Updated List: [8, 9, 10, 11, 12]


In [ ]:
numbers = [1, 2, 3, 4, 5]


updated_numbers = [i ** 7 for i in numbers]


print("Original List:", numbers)
print("Updated List:", updated_numbers)


Original List: [1, 2, 3, 4, 5]
Updated List: [1, 128, 2187, 16384, 78125]


In [ ]:
s=(1,2,3,4,5)
supdatednumber=[i-2 for i in s]
print("original list: ", s)
print("updated list: ", supdatednumber)

original list:  (1, 2, 3, 4, 5)
updated list:  [-1, 0, 1, 2, 3]


In [ ]:
m=[]
for i in s:
  if i>3:
    m.append(i)
print(m)

[4, 5]


In [ ]:

k=[232,3,433,383,3222,]
k

[232, 3, 433, 383, 3222]

In [ ]:
# day(20/1/25)
import numpy as np
j=[5,7,4,35,44,8]
d=np.array(j)

In [ ]:
type(d)

numpy.ndarray

In [ ]:
d.shape# shape is dimention is a method used to get shape dimention order "(order)",only used in array numpy

(6,)

In [ ]:
j.shape # j is an list but not an array of numpy

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
d.ndim#gives the dimention of np array

1

In [ ]:
d.size

6

In [ ]:
j.size

AttributeError: 'list' object has no attribute 'size'

In [ ]:
s=[[4,8,44,43],[34,33,45,32],[636,363,67,87],[647,43,332,34],[747,443,321,334]]
arr=np.array(s)
arr

array([[  4,   8,  44,  43],
       [ 34,  33,  45,  32],
       [636, 363,  67,  87],
       [647,  43, 332,  34],
       [747, 443, 321, 334]])

In [ ]:
arr.shape

(5, 4)

In [ ]:
arr.size

20

In [ ]:
arr.reshape(5,4)

array([[  4,   8,  44,  43],
       [ 34,  33,  45,  32],
       [636, 363,  67,  87],
       [647,  43, 332,  34],
       [747, 443, 321, 334]])

In [ ]:
arr.reshape(5,43)

ValueError: cannot reshape array of size 20 into shape (5,43)

In [ ]:
a1=arr.reshape(2,2,5)
a1

array([[[  4,   8,  44,  43,  34],
        [ 33,  45,  32, 636, 363]],

       [[ 67,  87, 647,  43, 332],
        [ 34, 747, 443, 321, 334]]])

In [ ]:
a1.reshape(20)

array([  4,   8,  44,  43,  34,  33,  45,  32, 636, 363,  67,  87, 647,
        43, 332,  34, 747, 443, 321, 334])

In [ ]:
a1.shape

(2, 2, 5)

In [ ]:
a1.reshape(20,1)

array([[  4],
       [  8],
       [ 44],
       [ 43],
       [ 34],
       [ 33],
       [ 45],
       [ 32],
       [636],
       [363],
       [ 67],
       [ 87],
       [647],
       [ 43],
       [332],
       [ 34],
       [747],
       [443],
       [321],
       [334]])

In [ ]:
a1.ndim

3

In [ ]:
range(5,20)

range(5, 20)

In [ ]:
m=[1,2,3,4,5]
y=range(1,6,2)# step size is 2 here
m1=list(y)
m1

[1, 3, 5]

In [ ]:
tuple(range(-10,1))
#important thing to remember the negative step size in case of reverse traversal

(-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0)

In [ ]:
tuple(range(0,-10,-1))

(0, -1, -2, -3, -4, -5, -6, -7, -8, -9)

In [ ]:
tuple(range(-1,-10,-1))#going from -ve to +ve,so use -ve stepsize

(-1, -2, -3, -4, -5, -6, -7, -8, -9)

In [ ]:
b=np.arange(2.5,5.0,0.5)#arange method of numpy , simply makes an array of these range and display array by default if not converted
tuple(b)

(2.5, 3.0, 3.5, 4.0, 4.5)

In [ ]:
np.arange(2.5,5.0,0.5 )# as said above!)

array([2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
j=[5,87,23,46,62,84,80,45,77,33,80]
even=[]
odd=[]
for i in j:
  if(j.index(i)%2==0):
    even.append(i)
  else:
    odd.append(i)
print(even)
print(odd)

[5, 23, 62, 80, 77, 80]
[87, 46, 84, 45, 33]


In [ ]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j.index(80)


6

In [ ]:
j=[5,87,23,46,62,84,80,45,77,33,80]
even=[]
odd=[]
for i in range(len(j)):
  if(i%2==0):
    even.append(j[i])
  else:
    odd.append(j[i])
print(even)
print(odd)

[5, 23, 62, 80, 77, 80]
[87, 46, 84, 45, 33]


In [ ]:
np.mean(d)

17.166666666666668

In [ ]:

np.median(d)

7.5

In [ ]:
np.var(d)

257.8055555555556

In [ ]:
np.std(d)# std=(var)^1/2

16.056324472168455

In [ ]:
np.min(d)


4

In [ ]:
np.max(d)

44

In [ ]:
Q1=np.quantile(d,0.25)
Q2=np.quantile(d,0.50)
Q3=np.quantile(d,0.75)
print(f"Q1:{Q1}\nQ2:{Q2}\nQ3:{Q3}\n")


Q1:5.5
Q2:7.5
Q3:28.25



In [ ]:
#DISTRIBUTIONS: Normal, Binomial, Poison, uniform :values are in [0,1)
r=np.random.rand(3,5,2) # to create data that follows uniform dist, range[0,1)!
r

array([[[0.20682064, 0.23171419],
        [0.0768358 , 0.57573046],
        [0.04198477, 0.04270353],
        [0.32366986, 0.75501953],
        [0.33890879, 0.77235655]],

       [[0.38861896, 0.11716757],
        [0.8933767 , 0.2148225 ],
        [0.62299076, 0.21563009],
        [0.91258835, 0.50994413],
        [0.26394914, 0.19762677]],

       [[0.55204788, 0.8665422 ],
        [0.00553423, 0.52896786],
        [0.71019524, 0.28322283],
        [0.4285574 , 0.25158576],
        [0.91059012, 0.98991065]]])

In [ ]:
r.shape

(3, 5, 2)

In [ ]:

r.size

30

In [ ]:

r.ndim

3

In [ ]:
sd=np.random.randn(4,10) #-3 to +3 : range for std normal dist!
sd

array([[ 1.61824489e+00, -5.91966057e-01,  4.56787467e-01,
         3.13189893e+00, -1.37377859e+00,  5.49324893e-01,
         1.45315380e+00,  1.87796232e+00, -1.16222380e+00,
        -8.80695736e-02],
       [-7.00647111e-04,  4.81938957e-01,  2.31764827e-01,
         9.74113804e-01, -1.48033883e+00,  3.96578836e-01,
        -6.98345052e-01,  9.13372036e-01,  3.79133221e-01,
        -1.15132410e+00],
       [ 2.30429999e-01,  9.52017276e-01, -4.00063631e-01,
        -3.37385854e-01, -8.51320345e-01, -1.61937796e+00,
        -4.99240656e-02,  3.93959250e-01,  5.91181151e-01,
        -8.96207239e-01],
       [-7.89666212e-01,  8.73448377e-01, -6.87334509e-01,
        -1.31050856e+00,  7.76616635e-01,  8.42772435e-02,
         4.89769112e-01,  1.33491873e-01,  2.87365570e-01,
         4.72343578e-01]])

In [ ]:
sd.shape

(4, 10)

In [ ]:
sd.ndim

2

In [ ]:
np.random.normal(40,5,(4,8)) #in this form as(4,8)


array([[37.40322452, 46.59512188, 34.77333603, 42.10853231, 38.04038407,
        36.02345005, 34.20423171, 41.03735642],
       [38.6468436 , 37.60777517, 41.10306538, 45.09103852, 36.08842413,
        40.13008836, 31.09997009, 38.80817585],
       [40.82986072, 45.23517959, 39.11084914, 32.36706088, 39.28323451,
        45.13192538, 45.98272399, 41.89350327],
       [34.89195998, 37.82384282, 35.70082919, 43.0340762 , 34.03702575,
        39.41683631, 40.28586535, 38.54812893]])

In [ ]:
np.random.randint(10,50,5)

array([23, 27, 30, 25, 49])

In [ ]:
#day 2
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [ ]:
k=[]
for i in (h):
  # i=i+7
  k.append(i+7)
print(k)

[37, 27, 12, 15, 16]


In [ ]:
s=(6,2,3,9,7,5,8)
s


(6, 2, 3, 9, 7, 5, 8)

In [ ]:
r=[]
s1=list(s)
for i in s:
  r.append(i**2)
r1=tuple(r)
r1

(36, 4, 9, 81, 49, 25, 64)

In [ ]:
tuple(i**2 for i in s)

(36, 4, 9, 81, 49, 25, 64)

In [ ]:
for i in r:
  if i>50:
    print(i)

81
64


In [ ]:
tuple(i for i in r if i>50)


(81, 64)

In [ ]:
list(i for i in r if i>50)

[81, 64]

In [ ]:
import numpy as np
arr=np.array([20,50,30,70,80,40,36,54,23,98])
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [ ]:
arr+7

array([ 27,  57,  37,  77,  87,  47,  43,  61,  30, 105])

In [ ]:
arr+7

array([ 27,  57,  37,  77,  87,  47,  43,  61,  30, 105])

In [ ]:

arr%4

array([0, 2, 2, 2, 0, 0, 0, 2, 3, 2])

In [ ]:
arr>50

array([False, False, False,  True,  True, False, False,  True, False,
        True])

In [ ]:
arr[4:8:2]

array([80, 36])

In [ ]:
k=[36,4,9,81,49,25,64]
for i in range(len(k)):
  if k[i]>50:
    print(i)

3
6


In [ ]:

list(i for i in range(len(k)) if k[i]>50)


[3, 6]

In [ ]:

arr[arr>50]

array([70, 80, 54, 98])

In [ ]:
np.where(arr>50)


(array([3, 4, 7, 9]),)

In [ ]:
import numpy as np

# Generate a 7x7 array with random values between 0 and 1
a = np.random.rand(7, 7)

# Print the array
print(a)

[[0.4629067  0.25560643 0.51247516 0.89946117 0.44945513 0.37194842
  0.41069802]
 [0.95455042 0.94900921 0.93949094 0.96470479 0.78444518 0.07116362
  0.73316379]
 [0.03539653 0.7450563  0.09094194 0.16809841 0.00201421 0.21795726
  0.40610125]
 [0.08283907 0.38699489 0.97839436 0.88668006 0.48501149 0.80000785
  0.85975971]
 [0.23292749 0.86404606 0.44571712 0.34706275 0.14997588 0.79141782
  0.67224473]
 [0.19175261 0.11173712 0.38817894 0.0870539  0.5806816  0.71749743
  0.69048323]
 [0.48028901 0.59306961 0.69352834 0.81313655 0.80994819 0.37441667
  0.16667997]]


In [ ]:
import numpy as np

# Generate a 7x7 array with random double-digit integers between 10 and 99 (inclusive)
a = np.random.randint(10, 100, size=(7, 7))

# Print the array
print(a)

[[95 12 35 32 14 30 41]
 [89 83 35 77 90 89 38]
 [33 70 31 19 81 61 27]
 [60 17 80 45 84 27 14]
 [12 57 20 18 21 89 30]
 [57 80 82 69 52 69 71]
 [71 17 16 66 32 90 96]]


In [ ]:
a[:,6]

array([41, 38, 27, 14, 30, 71, 96])

In [ ]:

a[:,-1]


array([41, 38, 27, 14, 30, 71, 96])

In [ ]:

a[3,2]

80

In [ ]:
a[:3]

array([[95, 12, 35, 32, 14, 30, 41],
       [89, 83, 35, 77, 90, 89, 38],
       [33, 70, 31, 19, 81, 61, 27]])

In [ ]:
a[2:]

array([[33, 70, 31, 19, 81, 61, 27],
       [60, 17, 80, 45, 84, 27, 14],
       [12, 57, 20, 18, 21, 89, 30],
       [57, 80, 82, 69, 52, 69, 71],
       [71, 17, 16, 66, 32, 90, 96]])

In [ ]:
a[2:7:2]

array([[33, 70, 31, 19, 81, 61, 27],
       [12, 57, 20, 18, 21, 89, 30],
       [71, 17, 16, 66, 32, 90, 96]])

In [ ]:
a[2:7:2,]

array([[33, 70, 31, 19, 81, 61, 27],
       [12, 57, 20, 18, 21, 89, 30],
       [71, 17, 16, 66, 32, 90, 96]])

In [ ]:
a[2:7:2,1:5]

array([[70, 31, 19, 81],
       [57, 20, 18, 21],
       [17, 16, 66, 32]])

In [ ]:

a[2:5,2:6]

array([[31, 19, 81, 61],
       [80, 45, 84, 27],
       [20, 18, 21, 89]])

In [ ]:
a[2:5:2,2:6]

array([[31, 19, 81, 61],
       [20, 18, 21, 89]])

In [ ]:
a[2:5,2:6:3]

array([[31, 61],
       [80, 27],
       [20, 89]])

In [1]:
import pandas as pd
import seaborn as sns


In [2]:
sns.get_dataset_names()


['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [8]:
K=[5,6,4,6,6,54,'SH'
   ]
K

[5, 6, 4, 6, 6, 54, 'SH']

In [11]:
pd.Series(K)

0     5
1     6
2     4
3     6
4     6
5    54
6    SH
dtype: object

In [24]:
import numpy as np
m=np.random.randint(10,11,50)
m
n=np.random.randint(12,14,(4,3))
n

array([[12, 12, 12],
       [12, 13, 12],
       [12, 12, 13],
       [12, 12, 13]])

In [25]:
n.ndim

2

In [26]:
pd.DataFrame(n)

0   1   2
0  12  12  12
1  12  13  12
2  12  12  13
3  12  12  13

In [28]:
N=pd.DataFrame(n,columns=['roll no','age','marks'],index=[425,426,427,428])
print(N)

     roll no  age  marks
425       12   12     12
426       12   13     12
427       12   12     13
428       12   12     13


In [29]:
df=sns.load_dataset('tips')
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [30]:
type(df)

pandas.core.frame.DataFrame

In [31]:
df.shape

(244, 7)

In [32]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [34]:
df.shape[1]

7

In [37]:
df.columns[1]

'tip'

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [40]:
df['tip'].mean()

KeyError: 'fare'